env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
ignorePatterns: 
  - '**/*.js'
plugins:
  - react
  - '@typescript-eslint'
rules: {
  '@typescript-eslint/ban-ts-comment': off,
  '@typescript-eslint/no-non-null-assertion': off,
  'semi': ['error', 'always'],
  'semi-spacing': ['error', {'after': true, 'before': false}],
  'semi-style': ['error', 'last'],
  'no-extra-semi': 'error',
  'no-unexpected-multiline': 'error',
  'no-unreachable': 'error'
}
